[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
fetch.github = "vim-jp/vimdoc-ja"

[winresizer]
src.git = "https://github.com/simeji/winresizer"
fetch.github = "simeji/winresizer"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
fetch.github = "vim-skk/skkeleton"

[hlchunk]
src.git = "https://github.com/shellRaining/hlchunk.nvim"
fetch.github = "shellRaining/hlchunk.nvim"

[skkeleton_indicator]
src.git = "https://github.com/delphinus/skkeleton_indicator.nvim"
fetch.github = "delphinus/skkeleton_indicator.nvim"

[lazygit_nvim]
src.git = "https://github.com/kdheepak/lazygit.nvim"
fetch.github = "kdheepak/lazygit.nvim"

[denops-vim]
src.git = "https://github.com/vim-denops/denops.vim"
fetch.github = "vim-denops/denops.vim"
