[win32yank]
src.github_tag = "equalsraf/win32yank"
fetch.url = "https://github.com/equalsraf/win32yank/releases/download/$ver/win32yank-x64.zip"

["gh-fzgist"]
src.git = "https://github.com/Omochice/gh-fzgist"
fetch.github = "Omochice/gh-fzgist"

["mbusb"]
src.git = "https://github.com/s0racat/multibootusb"
fetch.github = "s0racat/multibootusb"
