# treefmt.nix
{ ... }:
{
  # Used to find the project root
  projectRootFile = "flake.nix";
  programs.nixfmt.enable = true;
  # Override the default settings generated by the above option
  settings.formatter.nixfmt.excludes = [ "**_sources**" ];
}
