# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  skkeleton = {
    pname = "skkeleton";
    version = "438737ec49bcf1303521bdcccb5e06ced7b60c5e";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "438737ec49bcf1303521bdcccb5e06ced7b60c5e";
      fetchSubmodules = false;
      sha256 = "sha256-beQDAlgM9E3Xy+xQMAIfqrc7/j5ahboHi2Wa8T8zQFU=";
    };
    date = "2024-09-28";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "4f448c4d1833a3a6e36bb6f6942b767105362b51";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "4f448c4d1833a3a6e36bb6f6942b767105362b51";
      fetchSubmodules = false;
      sha256 = "sha256-20tyG5KsORhOmRTqkOPj9f5pfXF5uoR4tejmutm/ePs=";
    };
    date = "2024-10-11";
  };
  winresizer = {
    pname = "winresizer";
    version = "9bd559a03ccec98a458e60c705547119eb5350f3";
    src = fetchFromGitHub {
      owner = "simeji";
      repo = "winresizer";
      rev = "9bd559a03ccec98a458e60c705547119eb5350f3";
      fetchSubmodules = false;
      sha256 = "sha256-5LR9A23BvpCBY9QVSF9PadRuDSBjv+knHSmdQn/3mH0=";
    };
    date = "2022-08-15";
  };
}
