# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hlchunk = {
    pname = "hlchunk";
    version = "474ec5d0f220158afa83aaefab32402e710d3032";
    src = fetchFromGitHub {
      owner = "shellRaining";
      repo = "hlchunk.nvim";
      rev = "474ec5d0f220158afa83aaefab32402e710d3032";
      fetchSubmodules = false;
      sha256 = "sha256-zXWMwUNvofGNjLVYK/pPW7b062zP/yqUMk6lj3zgZqs=";
    };
    date = "2025-05-06";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "3e019b331fbf9bd1d4539e7bd650a1c543125cee";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "3e019b331fbf9bd1d4539e7bd650a1c543125cee";
      fetchSubmodules = false;
      sha256 = "sha256-VDu8WypgpzY+Dd8KIPJXsvtBEwt5YiuGXn6HAUKCbIQ=";
    };
    date = "2025-05-05";
  };
  skkeleton_indicator = {
    pname = "skkeleton_indicator";
    version = "f08532787cf842b996c8a5065be7e85cd3376c1f";
    src = fetchFromGitHub {
      owner = "delphinus";
      repo = "skkeleton_indicator.nvim";
      rev = "f08532787cf842b996c8a5065be7e85cd3376c1f";
      fetchSubmodules = false;
      sha256 = "sha256-6pQdj7EcPZ5/F34Y6SERRxcgKO6KLVH/94Th78ucn2Y=";
    };
    date = "2025-04-30";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "84c7ad166541cf9b333a8b5c3854fa5ac2db6b38";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "84c7ad166541cf9b333a8b5c3854fa5ac2db6b38";
      fetchSubmodules = false;
      sha256 = "sha256-3iHzItu9r6H5GDBrqFx3ubW+F//MEDrCICa4OC4M2Gk=";
    };
    date = "2025-06-21";
  };
  winresizer = {
    pname = "winresizer";
    version = "9bd559a03ccec98a458e60c705547119eb5350f3";
    src = fetchFromGitHub {
      owner = "simeji";
      repo = "winresizer";
      rev = "9bd559a03ccec98a458e60c705547119eb5350f3";
      fetchSubmodules = false;
      sha256 = "sha256-5LR9A23BvpCBY9QVSF9PadRuDSBjv+knHSmdQn/3mH0=";
    };
    date = "2022-08-15";
  };
}
